### ISSUE TITLE
TypeError when choosing nickname

### ISSUE THREAD

**Issue by ghost** [AndrewBelt/hack.chat#143] opened 2017-10-31 13:56 UTC
Hello.

I successfully installed everything, when npm start, it works.

I go on a random generated chat like banana, I put my nick, I click "OK" then:
Server disconnected. Attempting to reconnect...

and on the server console:

                        socket._receiver.flush();
                                         ^

TypeError: socket._receiver.flush is not a function
    at WebSocket.<anonymous> (/root/hack.chat/server.js:64:21)
    at emitOne (events.js:77:13)
    at WebSocket.emit (events.js:169:7)
    at Receiver._ultron.on._receiver.onmessage (/root/hack.chat/node_modules/ws/lib/WebSocket.js:146:47)
    at Receiver.dataMessage (/root/hack.chat/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/root/hack.chat/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/root/hack.chat/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/root/hack.chat/node_modules/ws/lib/Receiver.js:139:10)
    at Socket.<anonymous> (/root/hack.chat/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:77:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hack.chat@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hack.chat@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-31T13_59_06_273Z-debug.log

data contained in /root/.npm/_logs/2017-10-31T13_59_06_273Z-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v4.8.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hack.chat@1.0.0~prestart: hack.chat@1.0.0
6 info lifecycle hack.chat@1.0.0~start: hack.chat@1.0.0
7 verbose lifecycle hack.chat@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle hack.chat@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/hack.chat/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
9 verbose lifecycle hack.chat@1.0.0~start: CWD: /root/hack.chat
10 silly lifecycle hack.chat@1.0.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle hack.chat@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle hack.chat@1.0.0~start: Failed to exec start script
13 verbose stack Error: hack.chat@1.0.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at EventEmitter.emit (events.js:172:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:862:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
14 verbose pkgid hack.chat@1.0.0
15 verbose cwd /root/hack.chat
16 verbose Linux 2.6.32-042stab123.9
17 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 verbose node v4.8.2
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error hack.chat@1.0.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the hack.chat@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Plz help

**Comment by raf924** [comment] 2017-10-31 18:48
It'd be nice if people went to browse the issues a bit before posting new ones : https://github.com/AndrewBelt/hack.chat/issues/136

**Comment by AndrewBelt** [comment] 2017-10-31 18:53
Thanks @raf924, duplicate of #136

**Closed as completed by AndrewBelt** 2017-10-31 18:53 UTC
