### ISSUE TITLE
TypeError: socket._receiver.flush is not a function

### ISSUE THREAD

**Issue by evilvlso** [AndrewBelt/hack.chat#152] opened 2018-02-28 14:47 UTC
[root@tenxun hack.chat-master]# node server.js 
Loaded config 'config.json'
Started server on 0.0.0.0:6060
/root/hack.chat-master/server.js:64
                        socket._receiver.flush();
                                         ^
TypeError: socket._receiver.flush is not a function
    at WebSocket.<anonymous> (/root/hack.chat-master/server.js:64:21)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver._receiver.onmessage (/root/hack.chat-master/node_modules/ws/lib/WebSocket.js:146:47)
    at Receiver.dataMessage (/root/hack.chat-master/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/root/hack.chat-master/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/root/hack.chat-master/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/root/hack.chat-master/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/root/hack.chat-master/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)

what is the problem?   thinks  !

**Comment by raf924** [comment] 2018-02-28 15:39
@evilvlso #136

**Comment by AndrewBelt** [comment] 2018-02-28 15:56
Yup, duplicate of #136

**Closed as completed by AndrewBelt** 2018-02-28 15:56 UTC
